[package]
name = "perftest"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
fastrand = "2.1.0"
notan = { version = "0.12.1", features = ["egui"] }
memory-stats = "1.1.0"
image = "0.25.1"
rapier2d = "0.21.0"
simplify-polyline = "0.5.0"
contour = "0.13.1"
